defaults:
  - data: mapillary_v4
  - model/image_encoder: resnet_fpn
  - training
  - override hydra/launcher: "flow"
  - _self_
data:
  loading:
    train:
      batch_size: 9
model:
  name: localizer_bev_depth
  latent_dim: 128
  matching_dim: 8
  z_max: 32
  x_max: 32
  pixel_per_meter: ${data.pixel_per_meter}
  scale_range: [1,9]
  num_scale_bins: 33
  num_rotations: 64
  padding_matching: replicate
  norm_depth_scores: false
  normalize_scores_by_dim: false
  normalize_scores_by_num_valid: true
  normalize_features: false
  image_encoder:
    backbone:
      encoder: resnet101
  map_encoder:
    embedding_dim: 16
    output_dim: ${..matching_dim}
    num_classes: ${data.num_classes}
    backbone:
      encoder: vgg19
      pretrained: false
      output_scales: [0]
      num_downsample: 3
      decoder: [128, 64, 64]
      padding: replicate
    unary_prior: true
  bev_net:
    num_blocks: 4
    latent_dim: ${..latent_dim}
    output_dim: ${..matching_dim}
    confidence: true
