experiment:
  name: ???
  root: "manifold://psarlin/tree/maploc/experiments"
  gpus: 3
  seed: 0
training:
  elastic: true
  lr: 1e-4
  lr_scheduler: null
  finetune_from_checkpoint: null
  trainer:
    val_check_interval: 1000
    log_every_n_steps: 500
    limit_val_batches: 1000
    max_epochs: 1000
    gpus: ${experiment.gpus}
  checkpointing:
    monitor: "loss/total/val"
    save_top_k: 5
    mode: "min"
hydra:
  job:
    name: ${experiment.name}
  launcher:
    mode: local  # change to flow
    owner: ${oc.env:USER}
    entitlement: bigbasin_atn_arvr
    run_as_secure_group: llp_london_research
    resource_requirements:
      cpu: 56
      memory: 160g
      gpu: ${experiment.gpus}
      capabilities: [GPU_V100_HOST]
